/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entity.Answer;
import entity.Question;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;

/**
 *
 * @author Nam
 */
public class PanelQuestionContent extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuestionContent
     */
    Question question;
    JButton parent;
    public ArrayList<Component> compOption = new ArrayList();

    public PanelQuestionContent(Question question, JButton parent) {
        initComponents();
        this.question = question;
        this.parent = parent;
        txtContent.setText(question.getContent());
        if (question.isMultiple()) {
            for (Answer ans : question.getAnswers()) {
                JCheckBox cbx = new JCheckBox(ans.getContent());
                panelOption.add(cbx);
                compOption.add(cbx);
                cbx.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        checkChange();
                    }
                });
            }
        } else {
            ButtonGroup group = new ButtonGroup();
            for (Answer ans : question.getAnswers()) {
                JRadioButton rbtn = new JRadioButton(ans.getContent());
                panelOption.add(rbtn);
                compOption.add(rbtn);
                group.add(rbtn);
                rbtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        checkChange();
                    }
                });
            }
        }
    }

    private void checkChange() {
        boolean color = false;
        for (Component comp : compOption) {
            if (comp instanceof JCheckBox) {
                if (((JCheckBox) comp).isSelected()) {
                    color = true;
                    break;
                }
            } else if (((JRadioButton) comp).isSelected()) {
                color = true;
                break;
            }
        }
        if (color) {
            parent.setBackground(Color.GREEN);
        } else {
            parent.setBackground(Color.WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelOption = new javax.swing.JPanel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtContent.setEditable(false);
        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelOption.setLayout(new javax.swing.BoxLayout(panelOption, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(panelOption);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelOption;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
